server:
  port: 9999

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(1qtk2gdzU1UN7LpxZIf3KZvGWOqSty5cmGG/+MlJbsdISRwhA+yqVJuq500wKeriRyr0d8l6rEK3PtySZqCURjc+lojegVB5q5ChyHZRaqdXKAwJNVFOXxzaZwRulvXZ5PI3BnybpnyfQvvP0JBv116B/HiI8n0Akj9Gr8NLTxDy5s/kSi/aBA==)
    username: ENC(hAxpYyKJPZwmiqo4dZwxvQ==)
    password: ENC(NYRZpv9bTX+t9B5IrOgOBbjKdYx1Qe95)
  # JPA
  jpa:
    hibernate:
    ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

# jasypt
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

# logging
logging:
  level:
    com.ssg.shoppingcart: debug
    org.hibernate: info
